### ISSUE TITLE
serverless listed as a dependency

### ISSUE THREAD

**Issue by Iodine-** [activescott/serverless-aws-static-file-handler#1]
`serverless` should be listed as a devdependency to avoid unnecessary bundling of it into deployment packages of consuming applications.  `serverless-aws-static-file-handler` is currently adding 15MB to my deployment package because of this.

**Comment by activescott** [comment]
great feedback! Thank you! I'll try to get to this in the next few days. I'd be happy to merge a PR for this though ;)
