### ISSUE TITLE
Infinite loop of error page loading if error page is missing in custom builds

### ISSUE THREAD

**Issue by kraus-milan** [activescott/serverless-aws-static-file-handler#109]
Hi, when custom build is used (e.g. using webpack) and error.html is not added to the build, requests to missing file cause infinite loading of error.html file.

### Expected behavior:

- missing error.html is detected and `.get()` rejects returned promise
- or contents of error.html are inlined into code
- or at least add information about the importance of including error.html in the final build into README

### Actual behavior:

- infinite loop of loading of error.html

### Steps to reproduce the problem:

- use webpack to create custom build
- don't include error.html in the build
- request missing file

**Comment by activescott** [comment]
Thanks so much for taking the time to report this! So you happen to have a repo that I can use to repro this? If not, not a huge deal, I should be able to get it going based on your repro steps, would just save me some time to have a webpack config and such all worked out. 

Thanks again for reporting!

**Comment by kraus-milan** [comment]
Hi @activescott unfortunatelly the repo is private so I cannot share it. But this is the webpack config - nothing special, we just manually copy a few swagger static files and our api definition and serve them via you plugin:

```
const path = require('path');
const slsw = require('serverless-webpack');
const CopyPlugin = require('copy-webpack-plugin');
const tsconfig = require('../../tsconfig.base.json');

module.exports = {
  mode: 'development',
  devtool: 'source-map',
  entry: slsw.lib.entries,
  target: 'node',
  resolve: {
    extensions: ['.mjs', '.ts', '.js', '.json', '.tsx'],
    alias: Object.entries(tsconfig.compilerOptions.paths).reduce((acc, [aliasKey, aliasPath]) => {
      acc[aliasKey] = path.resolve(__dirname, '../..', aliasPath[0]);
      return acc;
    }, {}),
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  module: {
    rules: [
      {
        oneOf: [
          {
            test: /\.(ts|js)$/,
            exclude: [/node_modules/],
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
            },
          },
        ],
      },
    ],
  },

  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: path.resolve(__dirname, 'src', 'functions', 'openapi', 'index.html'),
          to: 'swagger-ui/',
        },
        {
          from: path.resolve(__dirname, '..', '..', 'node_modules', 'swagger-ui-dist', 'swagger-ui.css'),
          to: 'swagger-ui/',
        },
        {
          from: path.resolve(__dirname, '..', '..', 'node_modules', 'swagger-ui-dist', 'swagger-ui-bundle.js'),
          to: 'swagger-ui/',
        },
        {
          from: path.resolve(
            __dirname,
            '..',
            '..',
            'node_modules',
            'swagger-ui-dist',
            'swagger-ui-standalone-preset.js',
          ),
          to: 'swagger-ui/',
        },
        {
          from: path.resolve(__dirname, '..', '..', 'node_modules', 'swagger-ui-dist', 'favicon-32x32.png'),
          to: 'swagger-ui/',
        },
        {
          from: path.resolve(__dirname, '..', '..', 'node_modules', 'swagger-ui-dist', 'favicon-16x16.png'),
          to: 'swagger-ui/',
        },
      ],
    }),
  ],
};
```

We use `serverless-webpack` plugin to create and deploy the package to AWS.

Thank you for your work.

**Comment by activescott** [comment]
@kraus-milan I think v3.0.7 should take care of this. Let me know if I'm missing something!

**Comment by kraus-milan** [comment]
Looks good, thank you :+1:
