### ISSUE TITLE
CI link in PR template goes to dead site

### ISSUE THREAD

**Issue by tomchiverton** [activescott/serverless-aws-static-file-handler#119]
```
- [ ] All tests pass on our CI Server: https://travis-ci.org/activescott/serverless-aws-static-file-handler
```

This page has text that says it's been moved to https://www.travis-ci.com/activescott/serverless-aws-static-file-handler but that's not working either.

**Comment by activescott** [comment]
🤦‍♂️ Thanks :) It should go to https://github.com/activescott/serverless-aws-static-file-handler/actions instead.

**Comment by activescott** [comment]
Also in readme at https://github.com/activescott/serverless-aws-static-file-handler/blob/main/README.md?plain=1#L85
