### ISSUE TITLE
EMFILE: too many open files when running serverless deploy

### ISSUE THREAD

**Issue by Pilskalns** [activescott/serverless-aws-static-file-handler#122]
### Environment:

Win 10, 64bit.
Node v16.11.1
Serverless framework installed as a global package (`npm i -g serverless`)

### Steps to reproduce the problem:
1. Fresh Serverless project (`serverless` + `npm init` + `git init`)
2. Run `serverless deploy` - all ok
3. Run `npm install serverless-aws-static-file-handler`
4. Run `serverless deploy` - sls process fails with 
```
Serverless Error ----------------------------------------

  Cannot read file node_modules\tabtab\node_modules\rxjs\_esm5\internal\operators\distinctUntilKeyChanged.js due to: EMFILE: too many open files, open 'xxxxxx\node_modules\tabtab\node_modules\rxjs\_esm5\internal\operators\distinctUntilKeyChanged.js'
```
### Actual behavior:

Upon inspection what is happening on disk, this package adds 673 dependency packages and 163MB to `node_modules`, including it installs once more `serverless` package with dependencies (again, I have it as a global package in the OS).

### Expected behavior:

When I run `npm i serverless-aws-static-file-handler` it would not install serverless again with its dependencies.

----

I don't understand where all the dependencies really comes from, is it due sls being listed in `peerDependencies`? I could not find a way how to tell npm not to install those.

**Comment by activescott** [comment]
I just went through these steps and it worked. My guess is that maybe you were using serverless v3.x and the version of `serverless-aws-static-file-handler` at the time you entered this issue had a peerDependency referencing v2 of serverless. However, just four days ago, beginning in v3.1.1 I did add support for serverless v3 in the peerDependencies. Check out releases: https://github.com/activescott/serverless-aws-static-file-handler/releases

Can you just try these steps again please? If you still have problems let me know the version of serverless you're using too please.

**Comment by Pilskalns** [comment]
Hi,

Just tried, technically it works.

Though it is still suboptimal - as soon as I add this package, it adds Serverless once more as a local package through dependency tree - 120+MB of packages in package-lock / node_modules.

I would suggest removing this peer-dependency at all:
1. Serverless itself is expected to be installed as a global package - it manages everything around CloudFormation templates, configuration etc, but is not required itself to be uploaded inside the Lambda.
2. One would expect to use Serverless Framework regardless, this package makes no sense without it.
3. There is a global AWS account limit to how many GB's can be stored in Lambda code, while I've not heard anyone reach it, for some folks it might be a consideration.
4. What I can see is that without this package (and huge dependency tree) the deploys are much faster, esp. if updating targeted functions with `serverless deploy function --function X`

**Comment by activescott** [comment]
@Pilskalns [Release v3.1.8](https://github.com/activescott/serverless-aws-static-file-handler/releases/tag/v3.1.8) removed the peer dependency (PR is linked there). So I'm closing this one. Please re-open or open another issue if you think I'm missing something. Thanks for reporting!!
