### ISSUE TITLE
Custom filename?

### ISSUE THREAD

**Issue by richardq26** [activescott/serverless-aws-static-file-handler#132]
all files downloaded = response.xlsx

**Comment by activescott** [comment]
hey @richardq26! Thanks for the note, but I didn't quite follow. Can you please give me some more detail? If you're having a problem or encountering a bug please give me enough information to reproduce the problem.

**Comment by activescott** [comment]
This issue seems to be stale so I'm closing it. If you want to respond with more info to help troubleshoot or a project to repro one of us can probably help!
