### ISSUE TITLE
binaryMediaTypes: */* in example causes issue with API Gateway CORS on OPTIONS request

### ISSUE THREAD

**Issue by danny-eugene** [activescott/serverless-aws-static-file-handler#165]
FYI, the line in the example serverless file actually does cause an issue, with CORS when using API Gateway.

It causes the OPTIONS preflight cors check to fail with the error message `{ "message": "Internal server error" }` as it gets inturpreted by the mock implementation as a binary field.

"`- "*/*" # Using */* doesn't have side effects that I can tell. The HTML response works fine.`

**Comment by activescott** [comment]
Thanks for reporting @danny-eugene !
