### ISSUE TITLE
Update to work with v2 payload?

### ISSUE THREAD

**Issue by thalesagapito** [activescott/serverless-aws-static-file-handler#47]
Not a bug, I was just trying to use the package and noticed it did not work with the API Gateway v2 payload format (https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html).

**What steps would be needed to adapt the package to work with v2?**
For now I've noticed the `event.path` variable would no longer work, it has been replaced with `event.rawPath`, but I don't know enough about the code to think of other changes. I'm willing to help though.

Any guidance would be welcome!

**Comment by tomchiverton** [comment]
event.path = event.rawPath;

in the handler isn't good enough, it then explodes on some error checking

```
"API Gateway method does not appear to be setup for Lambda Proxy Integration. Please confirm that `integration` property of the http event is not specified or set to `integration: proxy`. Missing lambda proxy property was resource","stack":["Error: API Gateway method does not appear to be setup for Lambda Proxy Integration. Please confirm that `integration` property of the http event is not specified or set to `integration: proxy`. Missing lambda proxy property was resource","    at Function.validateLambdaProxyIntegration (/var/task/node_modules/serverless-aws-static-file-handler/src/StaticFileHandler.js:247:13)","    at StaticFileHandler.get (/var/task/node_modules/serverless-aws-static-file-handler/src/StaticFileHandler.js:65:29)","    at Runtime.module.exports.dist [as handler] (/var/task/handler.js:28:21)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25
```
